version: '3'
services:
    workspace:
        build: '.'
        environment:
            - DISPLAY
            - QT_X11_NO_MITSHM=1
        privileged: true
        command: sleep infinity
        network_mode: host
        volumes: 
            - "../../..:/workspace"
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            - "$HOME/.Xauthority:/home/user/.Xauthority:rw"
